-- Estoque separado de pecas destinadas a venda pela internet.
-- Execute este arquivo no SQL Editor do Supabase antes de abrir o novo modulo.

create table if not exists public.estoque_pecas_venda (
  id bigint generated by default as identity primary key,
  data_cadastro date not null default current_date,
  nome_peca text not null,
  marca text not null,
  modelo text not null,
  versao text,
  codigo text,
  condicao text not null default 'Usada',
  local_armazenamento text not null,
  status text not null default 'Disponível',
  data_venda timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint estoque_pecas_venda_condicao_check check (condicao in ('Nova', 'Usada')),
  constraint estoque_pecas_venda_status_check check (status in ('Disponível', 'Vendido')),
  constraint estoque_pecas_venda_data_venda_check check (
    (status = 'Disponível' and data_venda is null)
    or (status = 'Vendido' and data_venda is not null)
  )
);

create index if not exists estoque_pecas_venda_status_idx
  on public.estoque_pecas_venda(status);

create index if not exists estoque_pecas_venda_codigo_idx
  on public.estoque_pecas_venda(codigo);

create index if not exists estoque_pecas_venda_modelo_idx
  on public.estoque_pecas_venda(modelo);

create or replace function public.atualizar_updated_at_estoque_pecas_venda()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists estoque_pecas_venda_updated_at on public.estoque_pecas_venda;
create trigger estoque_pecas_venda_updated_at
before update on public.estoque_pecas_venda
for each row
execute function public.atualizar_updated_at_estoque_pecas_venda();

alter table public.estoque_pecas_venda enable row level security;

drop policy if exists "estoque_pecas_venda_select" on public.estoque_pecas_venda;
create policy "estoque_pecas_venda_select"
on public.estoque_pecas_venda for select
using (true);

drop policy if exists "estoque_pecas_venda_insert" on public.estoque_pecas_venda;
create policy "estoque_pecas_venda_insert"
on public.estoque_pecas_venda for insert
with check (true);

drop policy if exists "estoque_pecas_venda_update" on public.estoque_pecas_venda;
create policy "estoque_pecas_venda_update"
on public.estoque_pecas_venda for update
using (true)
with check (true);

drop policy if exists "estoque_pecas_venda_delete" on public.estoque_pecas_venda;
create policy "estoque_pecas_venda_delete"
on public.estoque_pecas_venda for delete
using (true);

grant select, insert, update, delete on table public.estoque_pecas_venda to anon, authenticated;
grant usage, select on sequence public.estoque_pecas_venda_id_seq to anon, authenticated;
