-- Configuracao para fotos anexadas nas Ordens de Servico.
-- Execute este arquivo no SQL Editor do Supabase.

create table if not exists public.os_foto_upload_tokens (
  id bigint generated by default as identity primary key,
  token text not null unique,
  os_id bigint references public.ordens_servico(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.os_fotos (
  id bigint generated by default as identity primary key,
  os_id bigint references public.ordens_servico(id) on delete cascade,
  upload_token text,
  arquivo_path text not null,
  arquivo_nome text,
  tipo_arquivo text,
  tamanho_bytes bigint,
  origem text default 'computador',
  created_at timestamptz not null default now(),
  constraint os_fotos_os_ou_token_check check (os_id is not null or upload_token is not null)
);

create index if not exists os_fotos_os_id_idx on public.os_fotos(os_id);
create index if not exists os_fotos_upload_token_idx on public.os_fotos(upload_token);
create index if not exists os_foto_upload_tokens_token_idx on public.os_foto_upload_tokens(token);

alter table public.os_fotos enable row level security;
alter table public.os_foto_upload_tokens enable row level security;

drop policy if exists "os_fotos_select" on public.os_fotos;
create policy "os_fotos_select"
on public.os_fotos for select
using (true);

drop policy if exists "os_fotos_insert" on public.os_fotos;
create policy "os_fotos_insert"
on public.os_fotos for insert
with check (true);

drop policy if exists "os_fotos_update" on public.os_fotos;
create policy "os_fotos_update"
on public.os_fotos for update
using (true)
with check (true);

drop policy if exists "os_tokens_select" on public.os_foto_upload_tokens;
create policy "os_tokens_select"
on public.os_foto_upload_tokens for select
using (true);

drop policy if exists "os_tokens_insert" on public.os_foto_upload_tokens;
create policy "os_tokens_insert"
on public.os_foto_upload_tokens for insert
with check (true);

drop policy if exists "os_tokens_update" on public.os_foto_upload_tokens;
create policy "os_tokens_update"
on public.os_foto_upload_tokens for update
using (true)
with check (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'os-fotos',
  'os-fotos',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']::text[]
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "os_fotos_storage_select" on storage.objects;
create policy "os_fotos_storage_select"
on storage.objects for select
using (bucket_id = 'os-fotos');

drop policy if exists "os_fotos_storage_insert" on storage.objects;
create policy "os_fotos_storage_insert"
on storage.objects for insert
with check (bucket_id = 'os-fotos');

drop policy if exists "os_fotos_storage_update" on storage.objects;
create policy "os_fotos_storage_update"
on storage.objects for update
using (bucket_id = 'os-fotos')
with check (bucket_id = 'os-fotos');

drop policy if exists "os_fotos_storage_delete" on storage.objects;
create policy "os_fotos_storage_delete"
on storage.objects for delete
using (bucket_id = 'os-fotos');
